[package]
name = "wellen_bridge"
version = "0.1.0"
edition = "2021"
description = "Wellen Rust -> wasm bridge used by ROHD Wave Viewer"
repository = "https://github.com/intel/rohd-wave-viewer"
license = "BSD-3-Clause"
homepage = "https://github.com/intel/rohd-wave-viewer"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
flutter_rust_bridge = "=2.7.0"
wellen = { version = "0.20.1", features = ["serde1"] }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2"
lazy_static = "1.5"

[build-dependencies]
# Use the codegen version that matches the runtime.
flutter_rust_bridge_codegen = "=2.7.0"
