name: rohd_wave_viewer
description: "Wave viewer and wave vieweing utilities with ROHD."
homepage: https://intel.github.io/rohd-website/
repository: https://github.com/intel/rohd-wave-viewer
version: 0.0.1
issue_tracker: https://github.com/intel/rohd-wave-viewer/issues

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  devtools_app_shared: ^0.0.5
  cupertino_icons: ^1.0.6
  flutter_fancy_tree_view: ^1.4.1
  bloc: ^8.0.0
  flutter_bloc: ^8.0.0
  google_fonts: ^6.1.0
  equatable: ^2.0.5
  module_structure_api:
    path: ./packages/module_structure_api
  module_structure_repository:
    path: ./packages/module_structure_repository
  mocktail: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.6
  test: ^1.24.9
  
flutter:
  uses-material-design: true
