#!/usr/bin/env bash

# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
#
# generate_coverage.sh
# Generates LCOV, HTML, and textual coverage summaries from the Flutter tests.
#
# 2026 August
# Author: Desmond Kirkpatrick <desmond.a.kirkpatrick@intel.com>

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
COVERAGE_DIR="$ROOT_DIR/coverage"
LCOV_FILE="$COVERAGE_DIR/lcov.info"
HTML_DIR="$COVERAGE_DIR/html"
GENERATE_SVG=false

while (($# > 0)); do
  case "$1" in
    --generate-svg)
      GENERATE_SVG=true
      ;;
    *)
      printf 'error: unknown option: %s\n' "$1" >&2
      exit 2
      ;;
  esac
  shift
done

bash "$ROOT_DIR/scripts/verify_flutter_version.sh"

require_tool() {
  command -v "$1" >/dev/null 2>&1 || {
    printf 'error: required tool not found: %s\n' "$1" >&2
    exit 2
  }
}

require_tool genhtml
require_tool lcov

rm -rf "$HTML_DIR"

printf 'Running Flutter tests with coverage...\n'
make -C "$ROOT_DIR" test \
  ARGS="--coverage ${COVERAGE_TEST_ARGS:-} test"

[[ -s "$LCOV_FILE" ]] || {
  printf 'error: coverage output is missing or empty: %s\n' "$LCOV_FILE" >&2
  exit 1
}

# Rust bridge bindings are generated by flutter_rust_bridge and tested through
# the Rust crate; they are not application Dart source.
lcov --remove "$LCOV_FILE" 'packages/dart_wellen/lib/src/rust/*.dart' \
  --output-file "$LCOV_FILE"

genhtml \
  --output-directory "$HTML_DIR" \
  --title 'ROHD Wave Viewer Coverage' \
  "$LCOV_FILE"

printf '\n'
coverage_summary="$(lcov --summary "$LCOV_FILE" 2>&1)"
printf '%s\n' "$coverage_summary"
printf '\nHTML report: %s\n' "$HTML_DIR/index.html"

if [[ "$GENERATE_SVG" == true ]]; then
  coverage_percent="$(
    printf '%s\n' "$coverage_summary" |
      awk '
        /lines[.]*:/ {
          if (match($0, /[0-9]+([.][0-9]+)?%/)) {
            value = substr($0, RSTART, RLENGTH)
            sub(/%$/, "", value)
            print value
            exit
          }
        }
      '
  )"
  if [[ -z "$coverage_percent" ]]; then
    printf 'error: could not extract line coverage percentage\n' >&2
    exit 1
  fi

  coverage_color="$(
    awk -v percentage="$coverage_percent" 'BEGIN {
      if (percentage >= 90) {
        print "#4c1"
      } else if (percentage >= 80) {
        print "#97ca00"
      } else if (percentage >= 70) {
        print "#dfb317"
      } else if (percentage >= 60) {
        print "#fe7d37"
      } else {
        print "#e05d44"
      }
    }'
  )"
  badge_text="${coverage_percent}%"
  text_width=$((${#badge_text} * 63))
  label_width=63
  value_width=$((text_width / 10 + 10))
  total_width=$((label_width + value_width))

  cat > /tmp/coverage-badge.svg << EOF
<svg xmlns="http://www.w3.org/2000/svg" width="${total_width}" height="20" role="img" aria-label="coverage: ${badge_text}">
    <title>coverage: ${badge_text}</title>
    <linearGradient id="s" x2="0" y2="100%">
        <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
        <stop offset="1" stop-opacity=".1"/>
    </linearGradient>
    <clipPath id="r">
        <rect width="${total_width}" height="20" rx="3" fill="#fff"/>
    </clipPath>
    <g clip-path="url(#r)">
        <rect width="${label_width}" height="20" fill="#555"/>
        <rect x="${label_width}" width="${value_width}" height="20" fill="${coverage_color}"/>
        <rect width="${total_width}" height="20" fill="url(#s)"/>
    </g>
    <g fill="#fff" text-anchor="middle" font-family="Verdana,Geneva,DejaVu Sans,sans-serif" text-rendering="geometricPrecision" font-size="110">
        <text aria-hidden="true" x="325" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="530">coverage</text>
        <text x="325" y="140" transform="scale(.1)" fill="#fff" textLength="530">coverage</text>
        <text aria-hidden="true" x="$((label_width * 10 + value_width * 5))" y="150" fill="#010101" fill-opacity=".3" transform="scale(.1)" textLength="${text_width}">${badge_text}</text>
        <text x="$((label_width * 10 + value_width * 5))" y="140" transform="scale(.1)" fill="#fff" textLength="${text_width}">${badge_text}</text>
    </g>
</svg>
EOF
  printf 'Generated SVG badge at /tmp/coverage-badge.svg\n'
fi