#!/usr/bin/env bash

# Copyright (C) 2024-2026 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
#
# wave_dev_mode.sh
# Configures Wave Viewer development dependency overrides.
#
# 2024 April
# Author: Desmond Kirkpatrick <desmond.a.kirkpatrick@intel.com>

set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
viewer_dir="$(cd -- "$script_dir/.." && pwd)"
cd "$viewer_dir"

mode="${1:-}"
overrides="pubspec_overrides.yaml"
source_state=".wave_dependency_sources"
marker="# Generated by scripts/wave_dev_mode.sh. Do not edit by hand."
legacy_member_overrides=(
  "packages/dart_wellen/pubspec_overrides.yaml"
)

default_rohd_path="$HOME/release/rohd"
rohd_git_url="${ROHD_GIT_URL:-https://github.com/intel/rohd.git}"
rohd_git_ref="${ROHD_GIT_REF:-main}"
rohd_path="${ROHD_LOCAL_PATH:-$default_rohd_path}"

default_viewer_git_url="$(git config --get remote.origin.url 2>/dev/null || true)"
default_viewer_git_url="${default_viewer_git_url:-https://github.com/intel/rohd-wave-viewer.git}"
default_viewer_git_ref="$(git branch --show-current 2>/dev/null || true)"
default_viewer_git_ref="${default_viewer_git_ref:-main}"
viewer_git_url="${WAVE_VIEWER_GIT_URL:-$default_viewer_git_url}"
viewer_git_ref="${WAVE_VIEWER_GIT_REF:-$default_viewer_git_ref}"

temporary_files=()
temporary_file=""
configured_overrides_required=0

cleanup_temporary_files() {
  if [[ "${#temporary_files[@]}" -gt 0 ]]; then
    rm -f -- "${temporary_files[@]}"
  fi
}

create_temporary_file() {
  temporary_file="$(mktemp "$viewer_dir/.wave_dev_mode.XXXXXX")"
  temporary_files+=("$temporary_file")
}

trap cleanup_temporary_files EXIT

dependency_constraint() {
  local package="$1"
  awk -v package="$package" '
    $1 == package ":" { print $2; exit }
  ' pubspec.yaml
}

for dependency in \
  rohd \
  rohd_hierarchy \
  rohd_waveform \
  rohd_devtools_widgets \
  dart_wellen; do
  if [[ -z "$(dependency_constraint "$dependency")" ]]; then
    echo "Could not find $dependency in pubspec.yaml." >&2
    exit 1
  fi
done

usage() {
  cat <<'USAGE'
Usage: scripts/wave_dev_mode.sh <mode>

Modes:
  manifest         Use hosted ROHD dependencies and workspace-local dart_wellen.
  configure-group  Configure one dependency bundle.
  local-rohd       Local rohd; hosted ROHD packages; local Wave Viewer packages.
  local-packages   Hosted rohd; local ROHD packages; local Wave Viewer packages.
  local-all        Local rohd, ROHD packages, and Wave Viewer packages.
  show             Print the current dependency configuration.

Dependency bundles:
  rohd              The fundamental rohd package.
  rohd-packages     rohd_hierarchy, rohd_waveform, and rohd_devtools_widgets.
  viewer-packages   Packages in this repository, currently dart_wellen.
  all               rohd and all ROHD packages; leaves viewer-packages unchanged.

Each bundle supports hosted, git, or local sources. The application itself
always remains local.

All Git-backed ROHD bundles share ROHD_GIT_URL and ROHD_GIT_REF. All
Local-backed ROHD bundles share ROHD_LOCAL_PATH. Wave Viewer Git packages use
WAVE_VIEWER_GIT_URL and WAVE_VIEWER_GIT_REF. Local Wave Viewer packages use
this repository's Pub workspace.

Set WAVE_PROMPT_SOURCE_VALUE=1 with configure-group to prompt for the applicable
Git repository:ref or local ROHD checkout path. Set WAVE_SOURCE_VALUE to provide
the same value non-interactively.

The default local ROHD checkout is ~/release/rohd. ROHD Git sources default to
https://github.com/intel/rohd.git at main. Wave Viewer Git sources default to
this checkout's origin and current branch.

Legacy aliases hosted-external, local-widgets, hr-he, lr-he, hr-le, and lr-le
remain supported.
USAGE
}

ensure_managed_or_absent() {
  local file="$1"

  if [[ -f "$file" ]] && ! grep -qxF "$marker" "$file"; then
    echo "$file exists and was not generated by scripts/wave_dev_mode.sh." >&2
    echo "Move or remove it before switching development modes." >&2
    exit 1
  fi
}

backup_overrides() {
  local backup="$overrides.disabled"
  local suffix=1

  if [[ ! -f "$overrides" ]]; then
    return
  fi

  while [[ -e "$backup" ]]; do
    backup="$overrides.disabled.$suffix"
    suffix=$((suffix + 1))
  done
  mv -- "$overrides" "$backup"
  echo "Saved the previous $overrides as $backup."
}

validate_source() {
  case "$1" in
    hosted|git|local) ;;
    *)
      echo "Invalid dependency source '$1'; expected hosted, git, or local." >&2
      exit 2
      ;;
  esac
}

display_git_source() {
  local url="$1"
  local ref="$2"

  case "$url" in
    https://github.com/*)
      url="${url#https://}"
      url="${url%.git}"
      ;;
  esac
  printf '%s:%s\n' "$url" "$ref"
}

display_local_path() {
  local path="$1"

  case "$path" in
    "$HOME") printf '~\n' ;;
    "$HOME"/*) printf '~/%s\n' "${path#"$HOME"/}" ;;
    *) printf '%s\n' "$path" ;;
  esac
}

configure_git_source() {
  local target="$1"
  local spec="$2"
  local url
  local ref

  if [[ "$spec" != *:* ]]; then
    echo "Git source '$spec' must use the format repository:ref." >&2
    exit 2
  fi

  url="${spec%:*}"
  ref="${spec##*:}"
  if [[ -z "$url" || -z "$ref" || "$ref" == //* ]]; then
    echo "Git source '$spec' must use the format repository:ref." >&2
    exit 2
  fi

  case "$url" in
    github.com/*) url="https://$url" ;;
  esac

  case "$target" in
    rohd)
      rohd_git_url="$url"
      rohd_git_ref="$ref"
      ;;
    viewer)
      viewer_git_url="$url"
      viewer_git_ref="$ref"
      ;;
    *)
      echo "Unsupported Git source target '$target'." >&2
      exit 2
      ;;
  esac
}

prompt_source_value() {
  local group="$1"
  local source="$2"
  local default_value
  local prompt
  local value

  if [[ "${WAVE_PROMPT_SOURCE_VALUE:-0}" != 1 ||
    "$source" == "hosted" ||
    ( "$group" == "viewer-packages" && "$source" == "local" ) ]]; then
    return
  fi
  if [[ ! -t 0 ]]; then
    echo "Interactive source prompting requires a terminal." >&2
    exit 2
  fi

  case "$group:$source" in
    viewer-packages:git)
      default_value="$(display_git_source "$viewer_git_url" "$viewer_git_ref")"
      prompt="Wave Viewer Git repository:ref: "
      ;;
    *:git)
      default_value="$(display_git_source "$rohd_git_url" "$rohd_git_ref")"
      prompt="Shared ROHD Git repository:ref: "
      ;;
    *:local)
      default_value="$(display_local_path "$rohd_path")"
      prompt="Shared local ROHD checkout path: "
      ;;
  esac

  IFS= read -e -r -i "$default_value" -p "$prompt" value
  WAVE_SOURCE_VALUE="${value:-$default_value}"
}

resolve_rohd_path() {
  case "$rohd_path" in
    '~') rohd_path="$HOME" ;;
    \~/*) rohd_path="$HOME/${rohd_path:2}" ;;
  esac

  if [[ ! -f "$rohd_path/pubspec.yaml" ]] ||
    ! grep -Eq '^name:[[:space:]]*rohd[[:space:]]*$' "$rohd_path/pubspec.yaml"; then
    echo "Could not find a ROHD checkout at $rohd_path." >&2
    echo "Set ROHD_LOCAL_PATH to a checkout rooted at the rohd package." >&2
    exit 1
  fi
  rohd_path="$(cd -- "$rohd_path" && pwd)"
}

resolve_widgets_path() {
  local widgets_path="$rohd_path/packages/rohd_devtools_widgets"

  if [[ ! -f "$widgets_path/pubspec.yaml" ]]; then
    widgets_path="$rohd_path/rohd_devtools_extension/packages/rohd_devtools_widgets"
  fi
  printf '%s\n' "$widgets_path"
}

validate_local_rohd() {
  resolve_rohd_path
}

validate_local_rohd_packages() {
  local widgets_path
  local package_path
  local missing=0

  resolve_rohd_path
  widgets_path="$(resolve_widgets_path)"
  for package_path in \
    "$rohd_path/packages/rohd_hierarchy/pubspec.yaml" \
    "$rohd_path/packages/rohd_waveform/pubspec.yaml" \
    "$widgets_path/pubspec.yaml"; do
    if [[ ! -f "$package_path" ]]; then
      echo "Missing local ROHD package: $package_path" >&2
      missing=1
    fi
  done

  if [[ "$missing" != 0 ]]; then
    exit 1
  fi
}

validate_local_viewer_packages() {
  if [[ ! -f "$viewer_dir/packages/dart_wellen/pubspec.yaml" ]]; then
    echo "Missing local Wave Viewer package: packages/dart_wellen/pubspec.yaml" >&2
    exit 1
  fi
}

append_git_dependency() {
  local output="$1"
  local package="$2"
  local url="$3"
  local ref="$4"
  local path="${5:-}"

  cat >>"$output" <<YAML
  $package:
    git:
      url: $url
      ref: $ref
YAML
  if [[ -n "$path" ]]; then
    printf '      path: %s\n' "$path" >>"$output"
  fi
}

append_rohd_dependency() {
  local output="$1"
  local package="$2"
  local source="$3"
  local path="$4"

  case "$source" in
    hosted) ;;
    git)
      append_git_dependency \
        "$output" "$package" "$rohd_git_url" "$rohd_git_ref" "$path"
      ;;
    local)
      if [[ -z "$path" ]]; then
        printf '  %s:\n    path: %s\n' "$package" "$rohd_path" >>"$output"
      else
        printf '  %s:\n    path: %s/%s\n' \
          "$package" "$rohd_path" "$path" >>"$output"
      fi
      ;;
  esac
}

generate_configured_overrides() {
  local output="$1"
  local rohd_source="$2"
  local rohd_packages_source="$3"
  local viewer_packages_source="$4"
  local widgets_path
  local dependency_overrides_required=0

  configured_overrides_required=0
  validate_source "$rohd_source"
  validate_source "$rohd_packages_source"
  validate_source "$viewer_packages_source"

  if [[ "$rohd_source" == "local" ]]; then
    validate_local_rohd
  fi
  if [[ "$rohd_packages_source" == "local" ]]; then
    validate_local_rohd_packages
  fi
  if [[ "$viewer_packages_source" == "local" ]]; then
    validate_local_viewer_packages
  fi

  cat >"$output" <<YAML
$marker
# This file is intentionally ignored by git.
YAML

  if [[ "$viewer_packages_source" != "local" ]]; then
    printf 'workspace:\n' >>"$output"
    configured_overrides_required=1
  fi

  if [[ "$rohd_source" != "hosted" ||
    "$rohd_packages_source" != "hosted" ||
    "$viewer_packages_source" == "git" ]]; then
    dependency_overrides_required=1
    configured_overrides_required=1
  fi

  if [[ "$dependency_overrides_required" == 1 ]]; then
    printf 'dependency_overrides:\n' >>"$output"
    append_rohd_dependency "$output" rohd "$rohd_source" ""
    append_rohd_dependency \
      "$output" rohd_hierarchy "$rohd_packages_source" packages/rohd_hierarchy
    append_rohd_dependency \
      "$output" rohd_waveform "$rohd_packages_source" packages/rohd_waveform

    if [[ "$rohd_packages_source" == "local" ]]; then
      widgets_path="$(resolve_widgets_path)"
      printf '  rohd_devtools_widgets:\n    path: %s\n' \
        "$widgets_path" >>"$output"
    else
      append_rohd_dependency \
        "$output" \
        rohd_devtools_widgets \
        "$rohd_packages_source" \
        packages/rohd_devtools_widgets
    fi

    if [[ "$viewer_packages_source" == "git" ]]; then
      append_git_dependency \
        "$output" \
        dart_wellen \
        "$viewer_git_url" \
        "$viewer_git_ref" \
        packages/dart_wellen
    fi
  fi

  chmod 0644 "$output"
}

install_configured_overrides() {
  local generated_overrides="$1"
  local legacy_override

  ensure_managed_or_absent "$overrides"
  for legacy_override in "${legacy_member_overrides[@]}"; do
    ensure_managed_or_absent "$legacy_override"
    if [[ -f "$legacy_override" ]]; then
      rm -f -- "$legacy_override"
      echo "Removed legacy workspace-member override $legacy_override."
    fi
  done

  if [[ "$configured_overrides_required" == 0 ]]; then
    backup_overrides
    rm -f -- "$generated_overrides"
    echo "Using hosted ROHD dependencies and workspace-local Wave Viewer packages."
  else
    backup_overrides
    mv -- "$generated_overrides" "$overrides"
    echo "Wrote $overrides with the configured dependency bundles."
  fi
}

generate_source_state() {
  local output="$1"
  local rohd_source="$2"
  local rohd_packages_source="$3"
  local viewer_packages_source="$4"

  cat >"$output" <<STATE
rohd=$rohd_source
rohd_packages=$rohd_packages_source
viewer_packages=$viewer_packages_source
rohd_git_url=$rohd_git_url
rohd_git_ref=$rohd_git_ref
rohd_local_path=$rohd_path
viewer_git_url=$viewer_git_url
viewer_git_ref=$viewer_git_ref
STATE
  chmod 0644 "$output"
}

write_configuration() {
  local rohd_source="$1"
  local rohd_packages_source="$2"
  local viewer_packages_source="$3"
  local persist_state="${4:-yes}"
  local generated_overrides
  local generated_state

  create_temporary_file
  generated_overrides="$temporary_file"
  generate_configured_overrides \
    "$generated_overrides" \
    "$rohd_source" \
    "$rohd_packages_source" \
    "$viewer_packages_source"

  if [[ "$persist_state" == "yes" ]]; then
    create_temporary_file
    generated_state="$temporary_file"
    generate_source_state \
      "$generated_state" \
      "$rohd_source" \
      "$rohd_packages_source" \
      "$viewer_packages_source"
  fi

  install_configured_overrides "$generated_overrides"
  if [[ "$persist_state" == "yes" ]]; then
    mv -- "$generated_state" "$source_state"
  else
    rm -f -- "$source_state"
  fi
}

load_source_state() {
  local package
  local saved_source

  if [[ ! -f "$source_state" ]]; then
    return
  fi

  while IFS='=' read -r package saved_source; do
    case "$package" in
      rohd) rohd_source="$saved_source" ;;
      rohd_packages) rohd_packages_source="$saved_source" ;;
      viewer_packages) viewer_packages_source="$saved_source" ;;
      rohd_hierarchy|rohd_waveform|rohd_devtools_widgets)
        rohd_packages_source="$saved_source"
        ;;
      git_url|rohd_git_url)
        [[ -v ROHD_GIT_URL ]] || rohd_git_url="$saved_source"
        ;;
      git_ref|rohd_git_ref)
        [[ -v ROHD_GIT_REF ]] || rohd_git_ref="$saved_source"
        ;;
      local_path|rohd_local_path)
        [[ -v ROHD_LOCAL_PATH ]] || rohd_path="$saved_source"
        ;;
      viewer_git_url)
        [[ -v WAVE_VIEWER_GIT_URL ]] || viewer_git_url="$saved_source"
        ;;
      viewer_git_ref)
        [[ -v WAVE_VIEWER_GIT_REF ]] || viewer_git_ref="$saved_source"
        ;;
    esac
  done <"$source_state"
}

write_group_configuration() {
  local group="${1:-}"
  local source="${2:-}"
  local rohd_source="hosted"
  local rohd_packages_source="hosted"
  local viewer_packages_source="local"
  local git_target

  if [[ "$#" -ne 2 ]]; then
    echo "Usage: $0 configure-group <rohd|rohd-packages|viewer-packages|all> <hosted|git|local>" >&2
    exit 2
  fi
  validate_source "$source"

  case "$group" in
    rohd|rohd-packages|package|widget|viewer-packages|viewer|all|all-rohd) ;;
    *)
      echo "Invalid dependency group '$group'." >&2
      echo "Expected rohd, rohd-packages, viewer-packages, or all." >&2
      exit 2
      ;;
  esac

  load_source_state

  case "$group:$source" in
    viewer-packages:git|viewer:git)
      echo "Git repository/ref is shared by all Git-backed Wave Viewer packages."
      ;;
    viewer-packages:local|viewer:local)
      echo "Local Wave Viewer packages use this repository's Pub workspace."
      ;;
    *:git)
      echo "Git repository/ref is shared by all Git-backed ROHD bundles."
      ;;
    *:local)
      echo "Local checkout path is shared by all Local-backed ROHD bundles."
      ;;
    *:hosted) ;;
  esac

  case "$group" in
    package|widget) group="rohd-packages" ;;
    viewer) group="viewer-packages" ;;
    all-rohd) group="all" ;;
  esac

  prompt_source_value "$group" "$source"

  case "$source" in
    git)
      if [[ -n "${WAVE_SOURCE_VALUE:-}" ]]; then
        if [[ "$group" == "viewer-packages" ]]; then
          git_target="viewer"
        else
          git_target="rohd"
        fi
        configure_git_source "$git_target" "$WAVE_SOURCE_VALUE"
      fi
      ;;
    local)
      if [[ "$group" != "viewer-packages" &&
        -n "${WAVE_SOURCE_VALUE:-}" ]]; then
        rohd_path="$WAVE_SOURCE_VALUE"
      fi
      ;;
    hosted) ;;
  esac

  case "$group" in
    rohd) rohd_source="$source" ;;
    rohd-packages) rohd_packages_source="$source" ;;
    viewer-packages) viewer_packages_source="$source" ;;
    all)
      rohd_source="$source"
      rohd_packages_source="$source"
      ;;
  esac

  write_configuration \
    "$rohd_source" \
    "$rohd_packages_source" \
    "$viewer_packages_source"
}

show_file() {
  local file="$1"

  if [[ -f "$file" ]]; then
    echo
    echo "$file:"
    cat "$file"
  fi
}

case "$mode" in
  configure-group)
    write_group_configuration "${2:-}" "${3:-}"
    ;;
  hosted-external|manifest|hr-he)
    write_configuration hosted hosted local no
    ;;
  local-rohd|lr-he)
    write_configuration local hosted local
    ;;
  local-packages|local-widgets|hr-le)
    write_configuration hosted local local
    ;;
  local-all|lr-le)
    write_configuration local local local
    ;;
  show)
    if [[ -f "$source_state" ]]; then
      echo "Dependency sources:"
      cat "$source_state"
    else
      echo "No saved dependency source selection; using the manifest baseline."
    fi
    if [[ -f "$overrides" ]]; then
      show_file "$overrides"
    else
      echo "No generated override file is present."
    fi
    ;;
  -h|--help|help|"")
    usage
    ;;
  *)
    usage >&2
    exit 2
    ;;
esac
